"""Sync document columns

Revision ID: 87342cc2aa04
Revises: 002
Create Date: 2026-07-14 14:55:39.512524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87342cc2aa04'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('documents', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('image_uri', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('source', sa.String(length=50), nullable=False, server_default='camera'))
    op.add_column('documents', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.alter_column('documents', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'confidence_score')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'image_uri')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'tags')
    # ### end Alembic commands ###
