"""Add UserAIPreferences and is_deleted to Conversation

Revision ID: 8941781505aa
Revises: 3a4f9f629851
Create Date: 2026-07-25 14:14:29.536351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8941781505aa'
down_revision: Union[str, None] = '3a4f9f629851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('detailed_responses', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ai_preferences_user_id'), 'user_ai_preferences', ['user_id'], unique=True)
    # 1. Add column as nullable=True
    op.add_column('conversations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    
    # 2. Update existing rows to False
    op.execute('UPDATE conversations SET is_deleted = FALSE WHERE is_deleted IS NULL')
    
    # 3. Alter column to nullable=False and add server_default
    op.alter_column('conversations', 'is_deleted',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_deleted')
    op.drop_index(op.f('ix_user_ai_preferences_user_id'), table_name='user_ai_preferences')
    op.drop_table('user_ai_preferences')
    # ### end Alembic commands ###
