"""create schemes table

Revision ID: c6e597b3ab16
Revises: 87342cc2aa04
Create Date: 2026-07-15 07:32:57.180028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6e597b3ab16'
down_revision: Union[str, None] = '87342cc2aa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('scheme_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eligibility', sa.String(), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('age_range', sa.String(length=50), nullable=False),
    sa.Column('income_limit', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('application_mode', sa.String(length=50), nullable=False),
    sa.Column('application_start', sa.String(length=50), nullable=False),
    sa.Column('application_end', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('official_website', sa.String(length=255), nullable=False),
    sa.Column('official_apply_link', sa.String(length=255), nullable=False),
    sa.Column('official_notification', sa.String(length=255), nullable=True),
    sa.Column('ministry', sa.String(length=255), nullable=False),
    sa.Column('launch_year', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.String(length=50), nullable=False),
    sa.Column('last_verified', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_index(op.f('ix_schemes_scheme_id'), 'schemes', ['scheme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schemes_scheme_id'), table_name='schemes')
    op.drop_table('schemes')
    # ### end Alembic commands ###
